name: Deploy to Firebase on develop push

on:
  push:
    branches:
      - develop
    # paths:
    #   - 'apps/functions/**'
  pull_request:
    branches:
      - develop
    # paths:
    #   - 'apps/functions/**'

jobs:
  build_and_deploy:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install packages
        run: yarn install

      - name: Run deployment
        timeout-minutes: 10
        run: yarn deploy:ci # --scope=functions
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_TOKEN }}'
          FIREBASE_PROJECT_ID: '${{ secrets.FIREBASE_DEV_PROJECT_ID }}'

          REACT_APP_FIREBASE_CONFIG: '${{ secrets.REACT_APP_FIREBASE_DEV_CONFIG }}'
          NODE_ENV: development
          PUBLIC_URL: https://pixou-dev.web.app
