name: Deploy to Firebase on develop push
'on':
  push:
    branches:
      - develop
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: |
          yarn install

      - name: Run deployment
        timeout-minutes: 3
        run: yarn deploy:ci
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_TOKEN }}'
          FIREBASE_PROJECT_ID: '${{ secrets.FIREBASE_DEV_PROJECT_ID }}'

          REACT_APP_FIREBASE_CONFIG: '${{ secrets.REACT_APP_FIREBASE_DEV_CONFIG }}'
